package com.self.Exceptions
import java.lang.Exception

class Exception1 {

	var obj = new remoteCalculatorService()

	try{
		obj.add(3, 4)
	}catch{
		//case e: ServerIsDownException => log.error(e, "the remote calculator service is unavailable. should have kept your trusty HP.")
	case e: Exception => println(e, "the remote calculator service is unavailable. should have kept your trusty HP.")
	} finally {
		obj.close()
	}
}